# Site
dummyentrytoshowniceimage: 'assets/images/encarnado_graos_math2__signed_sharp[A4_122dpi].jpg'  
dummyentrytoshownicetext: Fiction of Popular Music, Creative Computing, Research, NIME
name: "Tiago Brizolara"
title: "Tiago Brizolara"
description:
  pt_BR: "Ficção de Música Popular, Computação Criativa"
  en: "Fiction of Popular Music, Creative Computing, Research"
featured_description:
  pt_BR: "Destaques"
  en: "Featured"
recent_description:
  pt_BR: "Recente"
  en: "Recent"
logo: 'assets/images/assinatura-artistica.JPG'
favicon: 'assets/images/assinatura-artistica.JPG'
baseurl: /brizolara.github.io
#theme: mediumish-theme-jekyll
#google_analytics: 'UA-46278016-1'
#disqus: 'demowebsite' RECEIVING TOO MUCH SPAM...
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b' 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  tiago:
    name: Tiago
    display_name: Tiago
    avatar: 'assets/images/profile-effect-600x600.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: tiago.brizolara@gmail.com
    web: https://tiagobrizolara.com
    twitter: https://twitter.com/brizolara
    #instagram: https://www.instagram.com/tiago.brizolara
    description:
      pt_BR: "Compositor, criador, pesquisador, desenvolvedor. Da música instrumental até novas interfaces para expressão musical."
      en: "Composer, creator, researcher, developer. From instrumental music to new interfaces for music expression."

# john:
#   name: John
#   display_name: John?    
#   avatar: 'assets/images/avatar.png'
#   gravatar: b1cc14991db7a456fcd761680bbc8f81
#   email: wowthemesnet@gmail.com
#   web: https://www.wowthemes.net
#   twitter: https://twitter.com/wowthemesnet
#   description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-polyglot
  
# Language (polyglot plugin)
languages: ["pt_BR", "en"]
default_lang: "pt_BR"
exclude_from_localization: ["javascript", "images", "css", "README.md"]
parallel_localization: false # Windows users will need to disable parallel_localization on their machines by setting parallel_localization: false in the _config.yml
#lang_from_path: true

# Workaround for polyglot to function (https://github.com/untra/polyglot)
#sass:
#    sourcemap: never

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
