# Site
name: "Tiago Brizolara"
title: "Tiago Brizolara"
description: "Creative Computing, Research, NIME, Contemporary Music"
logo: 'assets/images/assinatura-artistica.JPG'
favicon: 'assets/images/assinatura-artistica.JPG'
baseurl: /brizolara.github.io
theme: mediumish-theme-jekyll
google_analytics: 'UA-46278016-1'  
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b' 
include: ["_pages"]
permalink: /:title/

# Above:
# baseurl: /brizolara.github.io
# TODO - remove Google Analytics and Mailchimp

# Authors
authors:
  tiago:
    name: Tiago
    display_name: Tiago
    avatar: 'assets/images/profile-effect-600x600.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: tiago.brizolara@gmail.com
    web: https://tiagobrizolara.com
    twitter: https://twitter.com/brizolara
    description:
      en: "Researcher, composer, creator, developer. From instrumental music to new interfaces for music expression."
      pt_BR: "Pesquisador, compositor, criador, desenvolvedor. Da música instrumental a novas interfaces para expressão musical."
  john:
    name: John
    display_name: John?    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  
#- jekyll-polyglot
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/

# Language (polyglot plugin)
#languages: ["en", "pt_BR"]
#default_lang: "en"
#exclude_from_localization: ["javascript", "images", "css", "README.md"]
#parallel_localization: true
#lang_from_path: true # Enables getting page language from the first or second path segment, 
                     # e.g de/first-one.md, or _posts/zh_Hans_HK/use-second-segment.md , if the lang frontmatter isn't defined.
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
