# Site
name: "Tiago Brizolara"
title: "Tiago Brizolara"
description: "Creative Computing, Research, NIME, Ficção de Música Popular"
logo: 'assets/images/assinatura-artistica.JPG'
favicon: 'assets/images/assinatura-artistica.JPG'
baseurl: / #/mediumish-theme-jekyll
theme: mediumish-theme-jekyll
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  tiago:
    name: Tiago
    display_name: Tiago
    avatar: 'assets/images/square-Tiago-Brizolara-3.jpg'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: tiago.brizolara@gmail.com
    web: https://www.tiagobrizolara.com
    twitter: https://twitter.com/brizolara
    description: "Researcher, composer, creator, developer. From instrumental music to new interfaces for music expression."
  john:
    name: John
    display_name: John?    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
